### ISSUE TITLE
petit problème pour les prénoms composés

### ISSUE THREAD

**Issue by Ttoile42** [corentin-ryr/Intranet-Mailchimp#3]
![Capture](https://user-images.githubusercontent.com/76117806/115588434-0c1ba380-a2cf-11eb-9931-c3e2d1c05e1e.PNG)

La majuscule de la seconde partie du prénom composé n'apparait pas.

**Comment by hugoqnc** [comment]
Issue solved in e2e1b4896ab0e2d601a05b35726732c417329958 !
